Update uwsgi_format logging to fix Keystone logs.
Add code to easily gather successful and failed keystone log events
in order to use them in a security dashboard.

Uwsgi_format multiline log items are being grokked improperly due to
multi-line errors. We need to properly negate all lines that should
be single line messages.

Issue: CIRRUS-5478
Change-Id: I09359a436d53c9326d1bfcdc51d0ac450902a562

diff --git a/templates/filter-uwsgi-format.conf.erb b/templates/filter-uwsgi-format.conf.erb
--- a/templates/filter-uwsgi-format.conf.erb
+++ b/templates/filter-uwsgi-format.conf.erb
@@ -1,26 +1,20 @@
 filter {
   if [type] == "uwsgi_format" {
     multiline {
-      negate => false
-      pattern => "^\[uwsgi-http key: "
-      what => "previous"
-      stream_identity => "%{host}.%{source}"
-    }
-    multiline {
-      negate => false
-      pattern => "^\[pid: "
+      negate => true
+      pattern => "(?:^\[pid|^%{TIMESTAMP_ISO8601}|^%{DAY} %{MONTH})"
       what => "previous"
       stream_identity => "%{host}.%{source}"
     }
     grok {
       match => [
-        "message", "^\[pid: %{NUMBER:pid}\|app: %{NUMBER:app}\|req: %{NUMBER:managed_requests}/%{NUMBER:total_requests}\] %{IP:remote_addr} \(\) \{%{NUMBER:cgi_vars} vars in %{NUMBER:cgi_vars_size} bytes\} \[%{DAY:day} %{MONTH:month}  %{MONTHDAY:monthday} %{TIME:time} %{YEAR:year}\] %{GREEDYDATA:logmessage}",
-        "message", "^\[pid: %{NUMBER:pid}\|app: %{NUMBER:app}\|req: %{NUMBER:managed_requests}/%{NUMBER:total_requests}\] %{IP:remote_addr} \(\) \{%{NUMBER:cgi_vars} vars in %{NUMBER:cgi_vars_size} bytes\} \[%{DAY:day} %{MONTH:month} %{MONTHDAY:monthday} %{TIME:time} %{YEAR:year}\] %{GREEDYDATA:logmessage}",
-        "message", "^\[pid: %{NUMBER:pid}\|app: %{NUMBER:app}\|req: %{NUMBER:managed_requests}/%{NUMBER:total_requests}\] %{IP:remote_addr}, %{IP:local_addr} \(\) \{%{NUMBER:cgi_vars} vars in %{NUMBER:cgi_vars_size} bytes\} \[%{DAY:day} %{MONTH:month}  %{MONTHDAY:monthday} %{TIME:time} %{YEAR:year}\] %{GREEDYDATA:logmessage}",
-        "message", "^\[pid: %{NUMBER:pid}\|app: %{NUMBER:app}\|req: %{NUMBER:managed_requests}/%{NUMBER:total_requests}\] %{IP:remote_addr}, %{IP:local_addr} \(\) \{%{NUMBER:cgi_vars} vars in %{NUMBER:cgi_vars_size} bytes\} \[%{DAY:day} %{MONTH:month} %{MONTHDAY:monthday} %{TIME:time} %{YEAR:year}\] %{GREEDYDATA:logmessage}",
-        "message", "^%{TIMESTAMP_ISO8601:logdate}%{SPACE}%{NUMBER:pid}?%{SPACE}?(?<loglevel>AUDIT|CRITICAL|DEBUG|INFO|TRACE|WARNING|ERROR) \[?\b%{NOTSPACE:module}\b\]?%{SPACE}?%{GREEDYDATA:logmessage}?"
+        "message", "(?m)^\[pid: %{NUMBER:pid}\|app: %{NUMBER:app}\|req: %{NUMBER:managed_requests}/%{NUMBER:total_requests}\] %{IP:remote_addr}, %{IP:local_addr} \(\) \{%{NUMBER:cgi_vars} vars in %{NUMBER:cgi_vars_size} bytes\} \[%{DAY:day} %{MONTH:month}?%{SPACE}?%{MONTHDAY:monthday} %{TIME:time} %{YEAR:year}\] %{GREEDYDATA:logmessage}",
+        "message", "(?m)^\[pid: %{NUMBER:pid}\|app: %{NUMBER:app}\|req: %{NUMBER:managed_requests}/%{NUMBER:total_requests}\] %{IP:remote_addr} \(\) \{%{NUMBER:cgi_vars} vars in %{NUMBER:cgi_vars_size} bytes\} \[%{DAY:day} %{MONTH:month}?%{SPACE}?%{MONTHDAY:monthday} %{TIME:time} %{YEAR:year}\] %{GREEDYDATA:logmessage}",
+        "message", "^%{TIMESTAMP_ISO8601:logdate}%{SPACE}%{NUMBER:pid}?%{SPACE}?(?<loglevel>AUDIT|CRITICAL|DEBUG|INFO|TRACE|WARNING|ERROR) \[?\b%{NOTSPACE:module}\b\]?%{SPACE}?%{GREEDYDATA:logmessage}?",
+        "message", "^%{DAY:day} %{MONTH:month}?%{SPACE}?%{MONTHDAY:monthday} %{TIME:time} %{YEAR:year} - %{GREEDYDATA:logmessage}"
       ]
       add_field => { "received_at" => "%{@timestamp}" }
+      overwrite => [ "message" ]
     }
     if [year] =~ /.+/ {
       mutate {
@@ -39,6 +33,40 @@ filter {
     <% end %>
 
     if ! ("_grokparsefailure" in [tags]) {
+      if "keystone_main_uwsgi" in [fields][tags] {
+        grok {
+          match => [
+            "logmessage", "^\[%{DATA}: (?<keystone_status>Successful Login) : %{DATA:keystone_request_id} : \(%{WORD:keystone_request_method}\) %{PATH:keystone_request_path} : %{IP:keystone_forwarded_for} : %{IP:keystone_remote_addr} : %{NOTSPACE} :%{DATA}: %{DATA:keystone_user_id} : ?%{DATA:keystone_project_id} : ?%{GREEDYDATA:keystone_roles}",
+            "logmessage", "^\[%{DATA:keystone_request_id} %{DATA}\] (?<keystone_status>Authorization failed.)%{DATA}%{IP:keystone_remote_addr}"
+          ]
+          tag_on_failure => []
+        }
+        if ! ("_grokparsefailure" in [tags]) {
+          mutate {
+            remove_field => [ "keystone_request_method", "keystone_request_path", "keystone_forwarded_for" ]
+            rename => { "keystone_status" => "[fields][keystone][status]" }
+            rename => { "keystone_request_id" => "[fields][keystone][request_id]" }
+            rename => { "keystone_remote_addr" => "[fields][keystone][remote_addr]" }
+            rename => { "keystone_user_id" => "[fields][keystone][user_id]" }
+            rename => { "keystone_project_id" => "[fields][keystone][project_id]" }
+            rename => { "keystone_roles" => "[fields][keystone][roles]" }
+          }
+          if ("Successful Login" in [fields][keystone][status]) {
+            mutate {
+              replace => { "[fields][keystone][status]" => "success" }
+            }
+          } else {
+            mutate {
+              replace => { "[fields][keystone][status]" => "failed" }
+            }
+          }
+        }
+        else {
+          mutate {
+            remove_tag => [ "_grokparsefailure" ]
+          }
+        }
+      }
       date {
         match => [ "logdate",
                    "yyyy-MM-dd HH:mm:ss.SSS",
